### ISSUE TITLE
Does not compile with dir_out specified on latest DevKitPro

### ISSUE THREAD

**Issue by d0k3** [mid-kid/CakeBrah#7]
Updated my DevKitPro today, last update was with the libctru 1.0.0 release. When dir_out is specified, the error message with both installations of DevKitPro is:
"Only the data segment can have a BSS!"
(when compiling utils.s).

Without dir_out specified everything is fine.

**Comment by mid-kid** [comment]
https://github.com/mid-kid/CakesForeveryWan/blob/master/Makefile#L27
Works fine on CakesFW. I'm using libctru 1.1.0 and devkitARM r45.
dir_out shouldn't affect linking. Check your ASFLAGS/LDFLAGS/ANYFLAGS don't override CakeBrah's.

**Comment by d0k3** [comment]
Oh well, you're right. I should have given the absolute output path. Sorry, closing this for now.
