### ISSUE TITLE
Update libkhax

### ISSUE THREAD

**Issue by Madridi7** [mid-kid/CakeBrah#9]
Programs that use libkhax in cakebrah can't be compiled anymore. The latest libkhax fixes that

**Comment by mid-kid** [comment]
Libkhax is already up-to-date. If I'm using a wrong branch or something please point out what I should use.

**Comment by Madridi7** [comment]
Thanks. I could've sworn it was not updated when I checked a few times around the time I opened the issue. Sorry for the useless issue :/

**Comment by mid-kid** [comment]
No problem, it's useful to me being notified about this, as I don't check very often.
